name: Generate projects
on:
  pull_request:
    types: [closed]
    branches:
      - master 
jobs:
  build:
    if: github.event.pull_request.merged == true
    name: Flutter Gallery - Merge
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.commit_secret }}
      - name: Install Flutter
        run: |
          git clone -b master https://github.com/flutter/flutter.git
          ls -a
          echo "::add-path::$RUNNER_WORKSPACE/gjkh/flutter/bin"
          echo "::add-path::$GITHUB_WORKSPACE/flutter/bin"
          echo "::add-path::$RUNNER_WORKSPACE/gjkh/flutter/bin/cache/dart-sdk/bin"
          echo "::add-path::$GITHUB_WORKSPACE/flutter/bin/cache/dart-sdk/bin"
          ./flutter/bin/flutter doctor
      - name: Get packages    
        run: |
          cd src/generator
          flutter config --enable-web
          flutter pub get
      - name: Generate Projects    
        run: |
          cd src/generator
          dart bin/generator.dart
      - name: Publish web to gh-pages 
        run: |
          cd build/web
          git init
          git config --global user.email flutter@jaimeblasco.com
          git config --global user.name gallery-bot
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/gallery-bot/gjkh.git
          git checkout -b gh-pages
          git add --all
          git commit -m "Update web"
          git push origin gh-pages -f       
      - name: Save changes in master
        run: |
          git config --global user.email flutter@jaimeblasco.com
          git config --global user.name gallery-bot
          git add --all
          git commit -m "Update web"
          git push origin master -f
