name: Generate projects
on:
  pull_request:
    types: [closed]
    branches:
      - master 
jobs:
  build:
    if: github.event.pull_request.merged == true
    name: Flutter Gallery - Merge
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.commit_secret }}
      - name: Cache Flutter
        id: cache-flutter
        uses: actions/cache@v1
        with:
          path: src/flutter
          key: flutter
          restore-keys: |
            flutter-master-
            flutter-
      - name: Install Flutter
        if: steps.cache-flutter.outputs.cache-hit != 'true'
        run: |
          cd src/
          git clone -b master https://github.com/flutter/flutter.git
          cd ../
          echo "::add-path::$GITHUB_WORKSPACE/src/flutter/bin"
          echo "::add-path::$GITHUB_WORKSPACE/src/flutter/bin/cache/dart-sdk/bin"
          ./src/flutter/bin/flutter doctor
      - name: Get packages    
        run: |
          cd src/generator
          flutter config --enable-web
          flutter pub get
      - name: Generate Projects    
        run: |
          cd src/generator
          dart bin/generator.dart
          echo "::set-output name=message::$(dart bin/pr_comment.dart)"
      - name: Publish web to gh-pages 
        run: |
          cd build/web
          git init
          git config --global user.email flutter@jaimeblasco.com
          git config --global user.name gallery-bot
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/gallery-bot/gjkh.git
          git checkout -b gh-pages
          git add --all
          git diff --quiet && git diff --staged --quiet || git commit -am 'Update web'
          git push origin gh-pages -f
          rm -rf .git*  
      - name: Save changes in master
        run: |
          git config --global user.email flutter@jaimeblasco.com
          git config --global user.name gallery-bot
          git add --all
          git commit -m "Autoroll-Update"
          git push origin master
      - name: Comment PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.commit_secret }}
        with:
          msg: "${{ steps.generator.outputs.message }}"
          check_for_duplicate_msg: true     
    

