name: Validate project
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Project validation
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache Flutter
        id: cache-flutter
        uses: actions/cache@v1
        with:
          path: src/flutter
          key: flutter
      - name: Install Flutter
        if: steps.cache-flutter.outputs.cache-hit != 'true'
        run: |
          cd src/
          git clone -b master https://github.com/flutter/flutter.git
          cd ../
          echo "::add-path::$GITHUB_WORKSPACE/src/flutter/bin"
          echo "::add-path::$GITHUB_WORKSPACE/src/flutter/bin/cache/dart-sdk/bin"
          ./src/flutter/bin/flutter doctor
      - name: Get packages    
        run: |
          cd src/generator
          flutter config --enable-web
          flutter pub get
      - name: Generate Projects
        id: generator    
        run: |
          cd src/generator
          dart bin/generator.dart
      - name: Comment PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.commit_secret }}
        with:
          msg: "${{ steps.generator.outputs.message }}"
          check_for_duplicate_msg: true     
    
