name: Generate projects
on:
  push:
    branches:
      - master 
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Try if git works
        run: |
          touch example.txt
          git config --global user.email flutter@jaimeblasco.com
          git config --global user.name gallery-bot
          git add --all
          git commit -m "Update web"
          git push origin master -f
